# Generated by Django 3.0.1 on 2019-12-23 23:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=32, unique=True)),
                ('data', models.DateField(auto_now=True)),
                ('prioridade', models.CharField(choices=[('+1', 'alto'), ('0', 'normal'), ('-1', 'baixo')], default='0', max_length=2)),
                ('autor', models.ForeignKey(default='anônimo', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-data'],
            },
        ),
    ]
