# Generated by Django 3.0.1 on 2019-12-24 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('minhascompras', '0003_auto_20191223_1931'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='prioridade',
            field=models.CharField(choices=[('0', 'normal'), ('+1', 'alto'), ('-1', 'baixo')], default='0', max_length=2),
        ),
    ]
