# Generated by Django 3.0.1 on 2019-12-26 18:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('minhascompras', '0004_auto_20191224_1534'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='item',
            options={'ordering': ['data']},
        ),
    ]
