# Generated by Django 3.0.1 on 2019-12-26 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('minhascompras', '0005_auto_20191226_1429'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='data',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
